/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_package;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AddProductsFrame extends javax.swing.JFrame {

    private ViewProductsFrame parentTableFrame;

    /**
     * Creates new form AddProductsFrame
     */
    public AddProductsFrame(ViewProductsFrame parentFrame) {
        this.parentTableFrame = parentFrame;
        initComponents();
        setResizable(false);
        setLocation(943, 145);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        categoryLabel.setText("New Products");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgSelector = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        selectImageButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        lblImagePreview = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        productNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        productPriceField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productQuantityField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        categoryNumber = new javax.swing.JLabel();
        incrementButton = new javax.swing.JButton();
        decrementButton = new javax.swing.JButton();
        categoryLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 239, 215));

        jPanel1.setBackground(new java.awt.Color(254, 203, 105));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectImageButton.setBackground(new java.awt.Color(190, 165, 49));
        selectImageButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectImageButton.setForeground(new java.awt.Color(255, 255, 255));
        selectImageButton.setText("Select an image");
        selectImageButton.setFocusable(false);
        selectImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(selectImageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 710, 170, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 66, 41));
        jLabel4.setText("IMAGE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 50, -1));

        submitButton.setBackground(new java.awt.Color(161, 134, 5));
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setFocusable(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 760, 90, 30));

        lblImagePreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        lblImagePreview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblImagePreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 150, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 66, 41));
        jLabel1.setText("PRODUCT NAME:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        productNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(productNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 330, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(110, 66, 41));
        jLabel2.setText("PRICE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 48, -1));

        productPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPriceFieldActionPerformed(evt);
            }
        });
        jPanel1.add(productPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 330, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 66, 41));
        jLabel3.setText("PRODUCT QUANTITY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, -1));

        productQuantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productQuantityFieldActionPerformed(evt);
            }
        });
        jPanel1.add(productQuantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 330, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(110, 66, 41));
        jLabel6.setText("CATEGORY:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 82, -1));

        categoryNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        categoryNumber.setForeground(new java.awt.Color(110, 66, 41));
        categoryNumber.setText("1");
        jPanel1.add(categoryNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 30, -1));

        incrementButton.setText("+");
        incrementButton.setFocusable(false);
        incrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementButtonActionPerformed(evt);
            }
        });
        jPanel1.add(incrementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        decrementButton.setText("-");
        decrementButton.setFocusable(false);
        decrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrementButtonActionPerformed(evt);
            }
        });
        jPanel1.add(decrementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        categoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoryLabel.setText("XXXXXXX");
        jPanel1.add(categoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 140, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add product font.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameFieldActionPerformed

    private void productPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceFieldActionPerformed

    private void productQuantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productQuantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productQuantityFieldActionPerformed

    private File selectedFile;
    private void selectImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectImageButtonActionPerformed

        imgSelector.setDialogTitle("Select Product Image");

        imgSelector.setAcceptAllFileFilterUsed(false);
        imgSelector.addChoosableFileFilter(
                new javax.swing.filechooser.FileNameExtensionFilter("Image Files (.png, .jpg)", "png", "jpg")
        );

        int result = imgSelector.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = imgSelector.getSelectedFile();

            String fileName = selectedFile.getName().toLowerCase();
            if (!fileName.endsWith(".png") && !fileName.endsWith(".jpg")) { // fixed logic
                JOptionPane.showMessageDialog(this, "Only PNG and JPG images are allowed");
                selectedFile = null; // reset selected file
                return;
            }

            // Show image preview immediately
            lblImagePreview.setIcon(new ImageIcon(
                    new ImageIcon(selectedFile.getAbsolutePath())
                            .getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH)
            ));
        }
    }//GEN-LAST:event_selectImageButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            String productName = productNameField.getText().trim();
            String priceText = productPriceField.getText().trim();
            String quantityText = productQuantityField.getText().trim();
            String categoryText = categoryNumber.getText().trim();

            // Simple validation
            if (productName.isEmpty() || priceText.isEmpty() || quantityText.isEmpty() || categoryText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill out all fields!");
                return;
            }

            float productPrice;
            int productQuantity;
            int category;

            try {
                productPrice = Float.parseFloat(priceText);
                productQuantity = Integer.parseInt(quantityText);
                category = Integer.parseInt(categoryText);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid number input!");
                return;
            }

            if (selectedFile == null) {
                JOptionPane.showMessageDialog(this, "Please select an image!");
                return;
            }

            File imagesDir = new File("images");
            if (!imagesDir.exists()) {
                imagesDir.mkdir();
            }

            File destFile = new File(imagesDir, System.currentTimeMillis() + "_" + selectedFile.getName());
            Files.copy(selectedFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

            // Confirmation message
            String message = "Please confirm new product:\n\n"
                    + "Name: " + productName + "\n"
                    + "Category: " + category + "\n"
                    + "Price: ₱" + productPrice + "\n"
                    + "Quantity: " + productQuantity + "\n"
                    + "Image: " + destFile.getAbsolutePath() + "\n\n"
                    + "Do you want to add this product?";

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    message,
                    "Confirm Add Product",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (confirm == JOptionPane.YES_OPTION) {

                ImageIcon scaledIcon = new ImageIcon(
                        new ImageIcon(destFile.getAbsolutePath())
                                .getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH)
                );

                DashboardFrame.addProductToCategory(
                        category,
                        scaledIcon,
                        productName,
                        String.valueOf(productPrice)
                );

                DatabaseManager.addAll(
                        productName,
                        category,
                        productPrice,
                        productQuantity,
                        destFile.getAbsolutePath()
                );

                parentTableFrame.refreshTable();

                JOptionPane.showMessageDialog(this, "✅ Product added successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "❌ Product add cancelled.");
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving image.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong.");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void decrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrementButtonActionPerformed
        String categoryNum = categoryNumber.getText();
        int totalCategoryNum = Integer.parseInt(categoryNum);

        if (totalCategoryNum > 1) {
            totalCategoryNum--;
            String show = String.valueOf(totalCategoryNum);

            categoryNumber.setText(show);
        }

        if (totalCategoryNum == 1) {
            categoryLabel.setText("New Products");
        } else if (totalCategoryNum == 2) {
            categoryLabel.setText("Bakery");
        } else if (totalCategoryNum == 3) {
            categoryLabel.setText("Butchery");
        } else if (totalCategoryNum == 4) {
            categoryLabel.setText("Seafoods");
        } else if (totalCategoryNum == 5) {
            categoryLabel.setText("Ready Meals");
        } else if (totalCategoryNum == 6) {
            categoryLabel.setText("Vegetables");
        } else if (totalCategoryNum == 7) {
            categoryLabel.setText("Fruits");
        } else if (totalCategoryNum == 8) {
            categoryLabel.setText("Grocery");
        } else if (totalCategoryNum == 9) {
            categoryLabel.setText("Snacks");
        } else if (totalCategoryNum == 10) {
            categoryLabel.setText("Desserts");
        } else if (totalCategoryNum == 11) {
            categoryLabel.setText("Wines");
        }
    }//GEN-LAST:event_decrementButtonActionPerformed

    private void incrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementButtonActionPerformed
        String categoryNum = categoryNumber.getText();
        int totalCategoryNum = Integer.parseInt(categoryNum);

        if (totalCategoryNum < 11) {
            totalCategoryNum++;
            String show = String.valueOf(totalCategoryNum);

            categoryNumber.setText(show);
        }

        switch (totalCategoryNum) {
            case 1:
                categoryLabel.setText("New Products");
                break;
            case 2:
                categoryLabel.setText("Bakery");
                break;
            case 3:
                categoryLabel.setText("Butchery");
                break;
            case 4:
                categoryLabel.setText("Seafoods");
                break;
            case 5:
                categoryLabel.setText("Ready Meals");
                break;
            case 6:
                categoryLabel.setText("Vegetables");
                break;
            case 7:
                categoryLabel.setText("Fruits");
                break;
            case 8:
                categoryLabel.setText("Grocery");
                break;
            case 9:
                categoryLabel.setText("Snacks");
                break;
            case 10:
                categoryLabel.setText("Desserts");
                break;
            case 11:
                categoryLabel.setText("Wines");
                break;
        }

    }//GEN-LAST:event_incrementButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductsFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryNumber;
    private javax.swing.JButton decrementButton;
    private javax.swing.JFileChooser imgSelector;
    private javax.swing.JButton incrementButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagePreview;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField productPriceField;
    private javax.swing.JTextField productQuantityField;
    private javax.swing.JButton selectImageButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
