/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_package;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class CartFrame extends javax.swing.JFrame {

    private DatabaseManager db;

    JPanel newPanel = new JPanel();

    public CartFrame(DatabaseManager db) {
        initComponents();
        this.db = db;
        setLocationRelativeTo(null);

        checkBoxSlot1.setSelected(false);
        checkBoxSlot2.setSelected(false);
        updateCheckoutButton(); // will show 0 items

        newPanel.setBackground(new Color(255, 255, 254));
        newPanel.setBounds(0, 0, 1600, 120);
        newPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.GRAY));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        myCartImage = new javax.swing.JLabel();
        myCartButton = new javax.swing.JLabel();
        cartCount = new javax.swing.JLabel();
        gotoLandingPanelLogo = new javax.swing.JLabel();
        gotoRegisterImage = new javax.swing.JLabel();
        gotoRegisterButton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel92 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cartPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblImage1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblPrice1 = new javax.swing.JLabel();
        cartNameLabel4 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        cartNameLabel7 = new javax.swing.JLabel();
        cartNameLabel8 = new javax.swing.JLabel();
        checkBoxSlot1 = new javax.swing.JCheckBox();
        checkBoxSlot2 = new javax.swing.JCheckBox();
        lblQnty1 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        removeButton1 = new javax.swing.JButton();
        removeButton2 = new javax.swing.JButton();
        lblName2 = new javax.swing.JLabel();
        lblPrice2 = new javax.swing.JLabel();
        btnMinus = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnPlus2 = new javax.swing.JButton();
        lblQnty2 = new javax.swing.JLabel();
        btnMinus2 = new javax.swing.JButton();
        lblImage2 = new javax.swing.JLabel();
        warningLabel2 = new javax.swing.JLabel();
        warningLabel1 = new javax.swing.JLabel();
        cartNameLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        lblDeliveryFee = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        subTotalLabel = new javax.swing.JLabel();
        voucherField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(251, 239, 215));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myCartImage.setBackground(new java.awt.Color(25, 145, 77));
        myCartImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        myCartImage.setForeground(new java.awt.Color(153, 153, 153));
        myCartImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart icon - test.png"))); // NOI18N
        myCartImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myCartImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myCartImageMouseExited(evt);
            }
        });
        jPanel6.add(myCartImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 30, -1, 37));

        myCartButton.setBackground(new java.awt.Color(25, 145, 77));
        myCartButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        myCartButton.setForeground(new java.awt.Color(153, 153, 153));
        myCartButton.setText("MY CART");
        jPanel6.add(myCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 70, -1, -1));

        cartCount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cartCount.setForeground(new java.awt.Color(255, 102, 102));
        cartCount.setText("0");
        jPanel6.add(cartCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 10, 20, -1));

        gotoLandingPanelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/dashboard logo.png"))); // NOI18N
        jPanel6.add(gotoLandingPanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 70));

        gotoRegisterImage.setBackground(new java.awt.Color(25, 145, 77));
        gotoRegisterImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gotoRegisterImage.setForeground(new java.awt.Color(153, 153, 153));
        gotoRegisterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/register icon - test.png"))); // NOI18N
        gotoRegisterImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gotoRegisterImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gotoRegisterImageMouseExited(evt);
            }
        });
        jPanel6.add(gotoRegisterImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 20, -1, -1));

        gotoRegisterButton.setBackground(new java.awt.Color(25, 145, 77));
        gotoRegisterButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gotoRegisterButton.setForeground(new java.awt.Color(153, 153, 153));
        gotoRegisterButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gotoRegisterButton.setText("ACCOUNT");
        jPanel6.add(gotoRegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 70, 210, 20));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1542, 96));

        jPanel2.setBackground(new java.awt.Color(228, 166, 107));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1542, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1542, -1));

        jPanel92.setBackground(new java.awt.Color(228, 166, 107));
        jPanel92.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/motto icon.png"))); // NOI18N
        jPanel92.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, 70));

        getContentPane().add(jPanel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1540, -1));

        cartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, 120));

        lblName1.setText("Product Name");
        jPanel1.add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblPrice1.setText("Product Price");
        jPanel1.add(lblPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        cartNameLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cartNameLabel4.setForeground(new java.awt.Color(153, 153, 153));
        cartNameLabel4.setText("Product");
        jPanel1.add(cartNameLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        lblTotal2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTotal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal2.setText("Total");
        jPanel1.add(lblTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 70, 20));

        cartNameLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cartNameLabel7.setForeground(new java.awt.Color(153, 153, 153));
        cartNameLabel7.setText("Actions");
        jPanel1.add(cartNameLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        cartNameLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cartNameLabel8.setForeground(new java.awt.Color(153, 153, 153));
        cartNameLabel8.setText("Quantity");
        jPanel1.add(cartNameLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        checkBoxSlot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSlot1ActionPerformed(evt);
            }
        });
        jPanel1.add(checkBoxSlot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, -1, -1));

        checkBoxSlot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSlot2ActionPerformed(evt);
            }
        });
        jPanel1.add(checkBoxSlot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        lblQnty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQnty1.setText("1");
        lblQnty1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(lblQnty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 40, 30));

        lblTotal1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblTotal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal1.setText("Total");
        jPanel1.add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 60, 20));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 880, 10));

        removeButton1.setBackground(new java.awt.Color(215, 118, 25));
        removeButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeButton1.setForeground(new java.awt.Color(255, 255, 255));
        removeButton1.setText("Remove");
        removeButton1.setBorder(null);
        removeButton1.setFocusable(false);
        removeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(removeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 90, 40));

        removeButton2.setBackground(new java.awt.Color(215, 118, 25));
        removeButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeButton2.setForeground(new java.awt.Color(255, 255, 255));
        removeButton2.setText("Remove");
        removeButton2.setBorder(null);
        removeButton2.setFocusable(false);
        removeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(removeButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 90, 40));

        lblName2.setText("Product Name");
        jPanel1.add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        lblPrice2.setText("Product Price");
        jPanel1.add(lblPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        btnMinus.setBackground(new java.awt.Color(255, 255, 254));
        btnMinus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(102, 102, 102));
        btnMinus.setText("-");
        btnMinus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnMinus.setFocusable(false);
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 40, 30));

        btnPlus.setBackground(new java.awt.Color(255, 255, 254));
        btnPlus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(102, 102, 102));
        btnPlus.setText("+");
        btnPlus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnPlus.setFocusable(false);
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 40, 30));

        btnPlus2.setBackground(new java.awt.Color(255, 255, 254));
        btnPlus2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlus2.setForeground(new java.awt.Color(102, 102, 102));
        btnPlus2.setText("+");
        btnPlus2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnPlus2.setFocusable(false);
        btnPlus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlus2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 40, 30));

        lblQnty2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQnty2.setText("1");
        lblQnty2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(lblQnty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 40, 30));

        btnMinus2.setBackground(new java.awt.Color(255, 255, 254));
        btnMinus2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMinus2.setForeground(new java.awt.Color(102, 102, 102));
        btnMinus2.setText("-");
        btnMinus2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnMinus2.setFocusable(false);
        btnMinus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinus2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 40, 30));
        jPanel1.add(lblImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, 120));

        warningLabel2.setForeground(new java.awt.Color(255, 51, 51));
        warningLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(warningLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 190, 20));

        warningLabel1.setForeground(new java.awt.Color(255, 51, 51));
        warningLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(warningLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 190, 20));

        cartNameLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cartNameLabel9.setForeground(new java.awt.Color(153, 153, 153));
        cartNameLabel9.setText("Total");
        jPanel1.add(cartNameLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        cartPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 900, 480));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(164, 113, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Order Summary");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Subtotal");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Delivery Fee");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 420, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Sub Total");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Order Summary");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnCheckout.setBackground(new java.awt.Color(215, 118, 25));
        btnCheckout.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("PROCEED TO CHECKOUT");
        btnCheckout.setFocusable(false);
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 390, 50));

        lblDeliveryFee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDeliveryFee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDeliveryFee.setText("0.00");
        jPanel3.add(lblDeliveryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 280, 20));

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(215, 118, 25));
        lblGrandTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGrandTotal.setText("0.00");
        jPanel3.add(lblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 280, 20));

        subTotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        subTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        subTotalLabel.setText("0.00");
        jPanel3.add(subTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 280, 20));
        jPanel3.add(voucherField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 230, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("APPLY");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 40));

        jLabel3.setText("Enter Voucher ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        cartPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 440, 430));

        getContentPane().add(cartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1540, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myCartImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myCartImageMouseEntered
        myCartButton.setForeground(new Color(101, 13, 2));
    }//GEN-LAST:event_myCartImageMouseEntered

    private void myCartImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myCartImageMouseExited
        myCartButton.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_myCartImageMouseExited

    private void gotoRegisterImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoRegisterImageMouseEntered
        gotoRegisterButton.setForeground(new Color(101, 13, 2));
    }//GEN-LAST:event_gotoRegisterImageMouseEntered

    private void gotoRegisterImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoRegisterImageMouseExited
        gotoRegisterButton.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_gotoRegisterImageMouseExited

    private int quantity1 = 1;
    private int quantity2 = 1;

    private float deliveryFee1 = 50.0f;
    private float deliveryFee2 = 30.0f;

// Selected products
    private Product selectedProduct1;
    private Product selectedProduct2;

// Load product 1
    public void loadProduct1(String productName) {
        selectedProduct1 = db.getProductByName(productName);
        if (selectedProduct1 != null) {
            lblName1.setText(selectedProduct1.getName());
            lblPrice1.setText("₱" + String.format("%.2f", selectedProduct1.getPrice()));

            ImageIcon icon = new ImageIcon(selectedProduct1.getImagePath());
            Image img = icon.getImage().getScaledInstance(lblImage1.getWidth(), lblImage1.getHeight(), Image.SCALE_SMOOTH);
            lblImage1.setIcon(new ImageIcon(img));

            quantity1 = 1;
            lblQnty1.setText(String.valueOf(quantity1));

            updatePrdctTotal1();
            updateDeliveryFee();        // ✅ recalc delivery
            updateCombinedSubtotal();
            updateCheckoutButton();
        }
    }

// Load product 2
    public void loadProduct2(String productName) {
        selectedProduct2 = db.getProductByName(productName);
        if (selectedProduct2 != null) {
            lblName2.setText(selectedProduct2.getName());
            lblPrice2.setText("₱" + String.format("%.2f", selectedProduct2.getPrice()));

            ImageIcon icon = new ImageIcon(selectedProduct2.getImagePath());
            Image img = icon.getImage().getScaledInstance(lblImage2.getWidth(), lblImage2.getHeight(), Image.SCALE_SMOOTH);
            lblImage2.setIcon(new ImageIcon(img));

            quantity2 = 1;
            lblQnty2.setText(String.valueOf(quantity2));

            updatePrdctTotal2();
            updateDeliveryFee();        // ✅ recalc delivery
            updateCombinedSubtotal();
            updateCheckoutButton();
        }
    }

    private void updateDeliveryFee() {
        float totalDelivery = 0;

        if (selectedProduct1 != null && checkBoxSlot1.isSelected()) {
            totalDelivery += deliveryFee1;
        }

        if (selectedProduct2 != null && checkBoxSlot2.isSelected()) {
            totalDelivery += deliveryFee2;
        }

        lblDeliveryFee.setText("₱" + String.format("%.2f", totalDelivery));
    }

// Update product 1 total
    private void updatePrdctTotal1() {
        if (selectedProduct1 != null) {
            float total = selectedProduct1.getPrice() * quantity1;
            lblTotal1.setText("₱" + String.format("%.2f", total));
            updateCombinedSubtotal();
        }
    }

// Update product 2 total
    private void updatePrdctTotal2() {
        if (selectedProduct2 != null) {
            float total = selectedProduct2.getPrice() * quantity2;
            lblTotal2.setText("₱" + String.format("%.2f", total));
            updateCombinedSubtotal();
        }
    }

// Update combined subtotal
    private void updateCombinedSubtotal() {
        float productTotal = 0;

        if (selectedProduct1 != null && checkBoxSlot1.isSelected()) {
            productTotal += selectedProduct1.getPrice() * quantity1;
        }

        if (selectedProduct2 != null && checkBoxSlot2.isSelected()) {
            productTotal += selectedProduct2.getPrice() * quantity2;
        }

        float deliveryTotal = 0;
        if (selectedProduct1 != null && checkBoxSlot1.isSelected()) {
            deliveryTotal += deliveryFee1;
        }
        if (selectedProduct2 != null && checkBoxSlot2.isSelected()) {
            deliveryTotal += deliveryFee2;
        }

        float grandTotal = productTotal + deliveryTotal;

        subTotalLabel.setText("₱" + String.format("%.2f", productTotal));   // product subtotal
        lblDeliveryFee.setText("₱" + String.format("%.2f", deliveryTotal)); // delivery fee
        lblGrandTotal.setText("₱" + String.format("%.2f", grandTotal));
    }

    private void checkBoxSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSlot1ActionPerformed
        updateDeliveryFee();
        updateCombinedSubtotal();
        updateCheckoutButton();

    }//GEN-LAST:event_checkBoxSlot1ActionPerformed


    private void checkBoxSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSlot2ActionPerformed
        updateDeliveryFee();
        updateCombinedSubtotal();
        updateCheckoutButton();
    }//GEN-LAST:event_checkBoxSlot2ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        if (selectedProduct1 != null && quantity1 < selectedProduct1.getStock()) {
            quantity1++;
            lblQnty1.setText(String.valueOf(quantity1));
            updatePrdctTotal1();
            updateDeliveryFee();        // ✅ update delivery fee
            updateCombinedSubtotal();
            updateCheckoutButton();
        } else {
            warningLabel1.setText("Out of stock!");
        }
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        if (selectedProduct1 != null && quantity1 > 1) {
            quantity1--;
            lblQnty1.setText(String.valueOf(quantity1));
            updatePrdctTotal1();
            updateDeliveryFee();
            warningLabel1.setText("");
            updateCombinedSubtotal();
            updateCheckoutButton();
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMinus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinus2ActionPerformed
        if (selectedProduct2 != null && quantity2 > 1) {
            quantity2--;
            lblQnty2.setText(String.valueOf(quantity2));
            updatePrdctTotal2();
            updateDeliveryFee();
            warningLabel2.setText("");
            updateCombinedSubtotal();
            updateCheckoutButton();
        }
    }//GEN-LAST:event_btnMinus2ActionPerformed

    private void btnPlus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlus2ActionPerformed
        if (selectedProduct2 != null && quantity2 < selectedProduct2.getStock()) {
            quantity2++;
            lblQnty2.setText(String.valueOf(quantity2));
            updatePrdctTotal2();
            updateDeliveryFee();        // ✅ update delivery fee
            updateCombinedSubtotal();
            updateCheckoutButton();
        } else {
            warningLabel2.setText("Out of stock!");
        }
    }//GEN-LAST:event_btnPlus2ActionPerformed

    private void removeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButton1ActionPerformed
        if (selectedProduct1 != null) {
            // Clear product info from UI
            lblName1.setText("");
            lblPrice1.setText("₱0.00");
            lblImage1.setIcon(null);
            lblQnty1.setText("0");
            lblTotal1.setText("₱0.00");

            // Deselect checkbox
            checkBoxSlot1.setSelected(false);

            // Reset quantity and selected product
            quantity1 = 0;
            selectedProduct1 = null;

            // Update delivery fee and grand total
            updateDeliveryFee();
            updateCombinedSubtotal();
            updateCheckoutButton();
        }
    }//GEN-LAST:event_removeButton1ActionPerformed

    private void removeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButton2ActionPerformed
        if (selectedProduct2 != null) {
            // Clear product info from UI
            lblName2.setText("");
            lblPrice2.setText("₱0.00");
            lblImage2.setIcon(null);
            lblQnty2.setText("0");
            lblTotal2.setText("₱0.00");

            // Deselect checkbox
            checkBoxSlot2.setSelected(false);

            // Reset quantity and selected product
            quantity2 = 0;
            selectedProduct2 = null;

            // Update delivery fee and grand total
            updateDeliveryFee();
            updateCombinedSubtotal();
            updateCheckoutButton();
        }
    }//GEN-LAST:event_removeButton2ActionPerformed

    private void updateCheckoutButton() {
    int total = 0;

    if (checkBoxSlot1.isSelected() && selectedProduct1 != null) {
        total += quantity1;
    }

    if (checkBoxSlot2.isSelected() && selectedProduct2 != null) {
        total += quantity2;
    }

    btnCheckout.setText(
        "Proceed to Checkout (" + total + ")" 
    );
}


    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMinus2;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPlus2;
    private javax.swing.JLabel cartCount;
    public javax.swing.JLabel cartNameLabel4;
    public javax.swing.JLabel cartNameLabel7;
    public javax.swing.JLabel cartNameLabel8;
    public javax.swing.JLabel cartNameLabel9;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JCheckBox checkBoxSlot1;
    private javax.swing.JCheckBox checkBoxSlot2;
    private javax.swing.JLabel gotoLandingPanelLogo;
    private javax.swing.JLabel gotoRegisterButton;
    private javax.swing.JLabel gotoRegisterImage;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblDeliveryFee;
    private javax.swing.JLabel lblGrandTotal;
    public javax.swing.JLabel lblImage1;
    public javax.swing.JLabel lblImage2;
    public javax.swing.JLabel lblName1;
    public javax.swing.JLabel lblName2;
    public javax.swing.JLabel lblPrice1;
    public javax.swing.JLabel lblPrice2;
    public javax.swing.JLabel lblQnty1;
    public javax.swing.JLabel lblQnty2;
    public javax.swing.JLabel lblTotal1;
    public javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel myCartButton;
    private javax.swing.JLabel myCartImage;
    private javax.swing.JButton removeButton1;
    private javax.swing.JButton removeButton2;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JTextField voucherField;
    private javax.swing.JLabel warningLabel1;
    private javax.swing.JLabel warningLabel2;
    // End of variables declaration//GEN-END:variables
}
