/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_package;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class CartFrame extends javax.swing.JFrame {
    
    JPanel newPanel = new JPanel();
    
    public CartFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        newPanel.setBackground(new Color(255, 255, 254));
        newPanel.setBounds(0, 0, 1600, 120);
        newPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.GRAY));
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        myCartImage = new javax.swing.JLabel();
        myCartButton = new javax.swing.JLabel();
        cartCount = new javax.swing.JLabel();
        gotoLandingPanelLogo = new javax.swing.JLabel();
        gotoRegisterImage = new javax.swing.JLabel();
        gotoRegisterButton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel92 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        paymentOptionsLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        aboutUsLabel = new javax.swing.JLabel();
        FAQsLabel = new javax.swing.JLabel();
        privacyPolicyLabel = new javax.swing.JLabel();
        cartPanel = new javax.swing.JPanel();
        cartNameLabel1 = new javax.swing.JLabel();
        cartPriceLabel1 = new javax.swing.JLabel();
        cartSlot1 = new javax.swing.JLabel();
        cartSlot2 = new javax.swing.JLabel();
        cartNameLabel2 = new javax.swing.JLabel();
        cartPriceLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cartNameLabel3 = new javax.swing.JLabel();
        cartNameLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(251, 239, 215));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myCartImage.setBackground(new java.awt.Color(25, 145, 77));
        myCartImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        myCartImage.setForeground(new java.awt.Color(153, 153, 153));
        myCartImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart icon - test.png"))); // NOI18N
        myCartImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myCartImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myCartImageMouseExited(evt);
            }
        });
        jPanel6.add(myCartImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 30, -1, 37));

        myCartButton.setBackground(new java.awt.Color(25, 145, 77));
        myCartButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        myCartButton.setForeground(new java.awt.Color(153, 153, 153));
        myCartButton.setText("MY CART");
        jPanel6.add(myCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 70, -1, -1));

        cartCount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cartCount.setForeground(new java.awt.Color(255, 102, 102));
        cartCount.setText("0");
        jPanel6.add(cartCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 10, 20, -1));

        gotoLandingPanelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/dashboard logo.png"))); // NOI18N
        jPanel6.add(gotoLandingPanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 70));

        gotoRegisterImage.setBackground(new java.awt.Color(25, 145, 77));
        gotoRegisterImage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gotoRegisterImage.setForeground(new java.awt.Color(153, 153, 153));
        gotoRegisterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/register icon - test.png"))); // NOI18N
        gotoRegisterImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gotoRegisterImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gotoRegisterImageMouseExited(evt);
            }
        });
        jPanel6.add(gotoRegisterImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 20, -1, -1));

        gotoRegisterButton.setBackground(new java.awt.Color(25, 145, 77));
        gotoRegisterButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gotoRegisterButton.setForeground(new java.awt.Color(153, 153, 153));
        gotoRegisterButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gotoRegisterButton.setText("ACCOUNT");
        jPanel6.add(gotoRegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 70, 210, 20));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1542, 96));

        jPanel2.setBackground(new java.awt.Color(228, 166, 107));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1542, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1542, -1));

        jPanel92.setBackground(new java.awt.Color(228, 166, 107));
        jPanel92.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/facebook icon.png"))); // NOI18N
        jPanel92.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 50, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pinterest icon.png"))); // NOI18N
        jPanel92.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 50, -1, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/instagram icon.png"))); // NOI18N
        jPanel92.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 50, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/follow us on icon.png"))); // NOI18N
        jPanel92.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 10, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/motto icon.png"))); // NOI18N
        jPanel92.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 70));

        paymentOptionsLabel.setBackground(new java.awt.Color(185, 85, 0));
        paymentOptionsLabel.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        paymentOptionsLabel.setForeground(new java.awt.Color(101, 13, 2));
        paymentOptionsLabel.setText("Payment Options");
        paymentOptionsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paymentOptionsLabelpaymentOptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paymentOptionsLabelpaymentOptionsMouseExited(evt);
            }
        });
        jPanel92.add(paymentOptionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("@Group4FinalProject - All rights reserved");
        jPanel92.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        aboutUsLabel.setBackground(new java.awt.Color(185, 85, 0));
        aboutUsLabel.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        aboutUsLabel.setForeground(new java.awt.Color(101, 13, 2));
        aboutUsLabel.setText("About Us");
        aboutUsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutUsLabelaboutUsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutUsLabelaboutUsMouseExited(evt);
            }
        });
        jPanel92.add(aboutUsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        FAQsLabel.setBackground(new java.awt.Color(185, 85, 0));
        FAQsLabel.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        FAQsLabel.setForeground(new java.awt.Color(101, 13, 2));
        FAQsLabel.setText("FAQs");
        FAQsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FAQsLabelFAQsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FAQsLabelFAQsMouseExited(evt);
            }
        });
        jPanel92.add(FAQsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        privacyPolicyLabel.setBackground(new java.awt.Color(185, 85, 0));
        privacyPolicyLabel.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        privacyPolicyLabel.setForeground(new java.awt.Color(101, 13, 2));
        privacyPolicyLabel.setText("Privacy & Policy");
        privacyPolicyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                privacyPolicyLabelprivacyPolicyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                privacyPolicyLabelprivacyPolicyMouseExited(evt);
            }
        });
        jPanel92.add(privacyPolicyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, -1, -1));

        getContentPane().add(jPanel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, -1));

        cartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartNameLabel1.setText("Product x Quantity");
        cartPanel.add(cartNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        cartPriceLabel1.setText("Product Price");
        cartPanel.add(cartPriceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        cartPanel.add(cartSlot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 120));
        cartPanel.add(cartSlot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, 120));

        cartNameLabel2.setText("Product Name");
        cartPanel.add(cartNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        cartPriceLabel2.setText("Product Price");
        cartPanel.add(cartPriceLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel1.setText("jLabel1");
        cartPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, -1, -1));

        cartNameLabel3.setText("Product Name");
        cartPanel.add(cartNameLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        cartNameLabel4.setText("Product x Quantity");
        cartPanel.add(cartNameLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        getContentPane().add(cartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1540, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myCartImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myCartImageMouseEntered
        myCartButton.setForeground(new Color(101,13,2));
    }//GEN-LAST:event_myCartImageMouseEntered

    private void myCartImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myCartImageMouseExited
        myCartButton.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_myCartImageMouseExited

    private void gotoRegisterImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoRegisterImageMouseEntered
        gotoRegisterButton.setForeground(new Color(101,13,2));
    }//GEN-LAST:event_gotoRegisterImageMouseEntered

    private void gotoRegisterImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoRegisterImageMouseExited
        gotoRegisterButton.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_gotoRegisterImageMouseExited

    private void paymentOptionsLabelpaymentOptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentOptionsLabelpaymentOptionsMouseEntered
        paymentOptionsLabel.setForeground(new Color(255, 255, 255));
        paymentOptionsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_paymentOptionsLabelpaymentOptionsMouseEntered

    private void paymentOptionsLabelpaymentOptionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentOptionsLabelpaymentOptionsMouseExited
        paymentOptionsLabel.setForeground(new Color(101, 13, 2));
    }//GEN-LAST:event_paymentOptionsLabelpaymentOptionsMouseExited

    private void aboutUsLabelaboutUsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsLabelaboutUsMouseEntered
        aboutUsLabel.setForeground(new Color(255, 255, 255));
        aboutUsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_aboutUsLabelaboutUsMouseEntered

    private void aboutUsLabelaboutUsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsLabelaboutUsMouseExited
        aboutUsLabel.setForeground(new Color(101, 13, 2));
    }//GEN-LAST:event_aboutUsLabelaboutUsMouseExited

    private void FAQsLabelFAQsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FAQsLabelFAQsMouseEntered
        FAQsLabel.setForeground(new Color(255, 255, 255));
        FAQsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_FAQsLabelFAQsMouseEntered

    private void FAQsLabelFAQsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FAQsLabelFAQsMouseExited
        FAQsLabel.setForeground(new Color(101, 13, 2));
    }//GEN-LAST:event_FAQsLabelFAQsMouseExited

    private void privacyPolicyLabelprivacyPolicyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_privacyPolicyLabelprivacyPolicyMouseEntered
        privacyPolicyLabel.setForeground(new Color(255, 255, 255));
        privacyPolicyLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_privacyPolicyLabelprivacyPolicyMouseEntered

    private void privacyPolicyLabelprivacyPolicyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_privacyPolicyLabelprivacyPolicyMouseExited
        privacyPolicyLabel.setForeground(new Color(101, 13, 2));
    }//GEN-LAST:event_privacyPolicyLabelprivacyPolicyMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FAQsLabel;
    private javax.swing.JLabel aboutUsLabel;
    private javax.swing.JLabel cartCount;
    public javax.swing.JLabel cartNameLabel1;
    public javax.swing.JLabel cartNameLabel2;
    public javax.swing.JLabel cartNameLabel3;
    public javax.swing.JLabel cartNameLabel4;
    private javax.swing.JPanel cartPanel;
    public javax.swing.JLabel cartPriceLabel1;
    public javax.swing.JLabel cartPriceLabel2;
    public javax.swing.JLabel cartSlot1;
    public javax.swing.JLabel cartSlot2;
    private javax.swing.JLabel gotoLandingPanelLogo;
    private javax.swing.JLabel gotoRegisterButton;
    private javax.swing.JLabel gotoRegisterImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JLabel myCartButton;
    private javax.swing.JLabel myCartImage;
    private javax.swing.JLabel paymentOptionsLabel;
    private javax.swing.JLabel privacyPolicyLabel;
    // End of variables declaration//GEN-END:variables
}
