/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main_package;

import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class CheckoutFrame extends javax.swing.JFrame {

    /**
     * Creates new form CheckoutFrame
     */
    private DatabaseManager dbManager;

    private Product selectedProduct1;
    private Product selectedProduct2;
    private int quantity1;
    private int quantity2;
    private float deliveryFee1;
    private float deliveryFee2;
private String email;

    public CheckoutFrame(DatabaseManager dbManager, CartFrame cFrame) {
        initComponents();

        this.dbManager = dbManager;

        setLocationRelativeTo(null);
        setResizable(false);

        // Set up navigation
        Listener.addLabelListener(gotoLandingPanelLogo, this, cFrame);

    }

    public void setCartData(Product p1, int q1, float d1, Product p2, int q2, float d2) {
        this.selectedProduct1 = p1;
        this.quantity1 = q1;
        this.deliveryFee1 = d1;

        this.selectedProduct2 = p2;
        this.quantity2 = q2;
        this.deliveryFee2 = d2;

        loadCartProductsToUI();
        generateTransactionNumber();
    }
    
    private void loadCartProductsToUI() {
    if (selectedProduct1 != null) {
        productName1.setText(selectedProduct1.getName());
        productPrice1.setText("₱" + String.format("%.2f", selectedProduct1.getPrice()));
        qty1.setText(String.valueOf(quantity1));
        lbl1Total.setText("₱" + String.format("%.2f", selectedProduct1.getPrice() * quantity1 + deliveryFee1));

        ImageIcon icon = new ImageIcon(selectedProduct1.getImagePath());
        Image img = icon.getImage().getScaledInstance(lblImage1.getWidth(), lblImage1.getHeight(), Image.SCALE_SMOOTH);
        lblImage1.setIcon(new ImageIcon(img));
    }

    if (selectedProduct2 != null) {
        productName2.setText(selectedProduct2.getName());
        productPrice2.setText("₱" + String.format("%.2f", selectedProduct2.getPrice()));
        qty2.setText(String.valueOf(quantity2));
        lbl2Total.setText("₱" + String.format("%.2f", selectedProduct2.getPrice() * quantity2 + deliveryFee2));

        ImageIcon icon = new ImageIcon(selectedProduct2.getImagePath());
        Image img = icon.getImage().getScaledInstance(lblImage2.getWidth(), lblImage2.getHeight(), Image.SCALE_SMOOTH);
        lblImage2.setIcon(new ImageIcon(img));
    }
    
    updateCombinedSubtotal();
}
    
    private String transactionNumber;
    
    private void generateTransactionNumber() {
    String timestamp = new java.text.SimpleDateFormat("yyyyMMddHHmmss").format(new java.util.Date());
    int random = (int)(Math.random() * 900 + 100); // 3-digit random number
    transactionNumber = "TXN-" + timestamp + "-" + random;
    
    transactionNumberLabel.setText(transactionNumber); // show in UI
}
    
 private void updateCombinedSubtotal() {
    float productTotal = 0;
    float deliveryTotal = 0;

    if (selectedProduct1 != null) {
        productTotal += selectedProduct1.getPrice() * quantity1;
        deliveryTotal += deliveryFee1;
    }
    if (selectedProduct2 != null) {
        productTotal += selectedProduct2.getPrice() * quantity2;
        deliveryTotal += deliveryFee2;
    }

    float grandTotal = productTotal + deliveryTotal;

    subTotalLabel.setText("₱" + String.format("%.2f", productTotal));
    lblDeliveryFee.setText("₱" + String.format("%.2f", deliveryTotal));
    lblGrandTotal.setText("₱" + String.format("%.2f", grandTotal));
}
 
 
    public void setEmail(String email) {
        if (email == null) {
            return; // safety check
        }
        String fullName = dbManager.getNameByEmail(email);
        String fullAddress = dbManager.retrieveFullAddress(email);
        String phoneNumber = dbManager.retrievePhoneNumber(email);

        nameLabel1.setText(fullName != null ? fullName : "");
        addressLabel.setText(fullAddress != null ? fullAddress : "");
        phoneNumberLabel.setText(phoneNumber);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        gotoLandingPanelLogo = new javax.swing.JLabel();
        cartPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cashOnDeliverPanel = new javax.swing.JPanel();
        cashOnDeliverCB = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cashOnDeliverySeperator = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        gcashPanel = new javax.swing.JPanel();
        gcashCheckBox = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        gcashSeperator = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        voucherField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        subTotalLabel = new javax.swing.JLabel();
        lblDeliveryFee = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        editAddressLabel1 = new javax.swing.JLabel();
        transactionNumberLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        warningLabel2 = new javax.swing.JLabel();
        warningLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        editAddressLabel = new javax.swing.JLabel();
        shippingAddressLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deliveryRider1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblImage5 = new javax.swing.JLabel();
        productName1 = new javax.swing.JLabel();
        productPrice1 = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();
        qty1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl1Total = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblImage4 = new javax.swing.JLabel();
        productPrice2 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        productName2 = new javax.swing.JLabel();
        qty2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl2Total = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        deliverRider2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(251, 239, 215));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gotoLandingPanelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/dashboard logo.png"))); // NOI18N
        gotoLandingPanelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(gotoLandingPanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 80));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1542, 96));

        cartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(164, 113, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Order Summary");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Total:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        cashOnDeliverPanel.setBackground(new java.awt.Color(255, 255, 255));
        cashOnDeliverPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cashOnDeliverPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cashOnDeliverCB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cashOnDeliverCB);
        cashOnDeliverCB.setForeground(new java.awt.Color(255, 51, 51));
        cashOnDeliverCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cashOnDeliverCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashOnDeliverCBActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel27.setText("Cash on Delivery");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cash on deliver icon.png"))); // NOI18N

        cashOnDeliverySeperator.setForeground(new java.awt.Color(204, 204, 204));

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Pay When you recieve");

        javax.swing.GroupLayout cashOnDeliverPanelLayout = new javax.swing.GroupLayout(cashOnDeliverPanel);
        cashOnDeliverPanel.setLayout(cashOnDeliverPanelLayout);
        cashOnDeliverPanelLayout.setHorizontalGroup(
            cashOnDeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashOnDeliverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashOnDeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashOnDeliverPanelLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                        .addComponent(cashOnDeliverCB)
                        .addContainerGap())
                    .addGroup(cashOnDeliverPanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(cashOnDeliverySeperator)
        );
        cashOnDeliverPanelLayout.setVerticalGroup(
            cashOnDeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashOnDeliverPanelLayout.createSequentialGroup()
                .addGroup(cashOnDeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cashOnDeliverPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cashOnDeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cashOnDeliverCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(cashOnDeliverySeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(cashOnDeliverPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 100));

        gcashPanel.setBackground(new java.awt.Color(255, 255, 255));
        gcashPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        gcashPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        gcashCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(gcashCheckBox);
        gcashCheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gcashCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcashCheckBoxActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel28.setText("GCash e-Wallet ");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gcash icon.png"))); // NOI18N

        gcashSeperator.setForeground(new java.awt.Color(204, 204, 204));

        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("GCash e-Wallet");

        javax.swing.GroupLayout gcashPanelLayout = new javax.swing.GroupLayout(gcashPanel);
        gcashPanel.setLayout(gcashPanelLayout);
        gcashPanelLayout.setHorizontalGroup(
            gcashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gcashPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(gcashCheckBox)
                .addContainerGap())
            .addComponent(gcashSeperator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(gcashPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gcashPanelLayout.setVerticalGroup(
            gcashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gcashPanelLayout.createSequentialGroup()
                .addGroup(gcashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gcashPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(gcashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(gcashCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(gcashSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel32)
                .addContainerGap())
        );

        jPanel3.add(gcashPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 400, 100));
        jPanel3.add(voucherField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 260, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("APPLY");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 130, 40));

        jLabel20.setText("Enter Voucher ");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Select Payment Method");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnCheckout.setBackground(new java.awt.Color(215, 118, 25));
        btnCheckout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("PLACE ORDER NOW");
        btnCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckout.setFocusable(false);
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 400, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Shipping Fee");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 400, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Order Detail");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(215, 118, 25));
        lblGrandTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGrandTotal.setText("0.00");
        jPanel3.add(lblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 280, 30));

        subTotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        subTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        subTotalLabel.setText("0.00");
        jPanel3.add(subTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 280, 20));

        lblDeliveryFee.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDeliveryFee.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDeliveryFee.setText("0.00");
        jPanel3.add(lblDeliveryFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 280, 20));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Subtotal");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        editAddressLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editAddressLabel1.setForeground(new java.awt.Color(51, 153, 255));
        editAddressLabel1.setText("View all methods>");
        editAddressLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(editAddressLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        transactionNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        transactionNumberLabel.setText("Transaction Number");
        jPanel3.add(transactionNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        cartPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 440, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningLabel2.setForeground(new java.awt.Color(255, 51, 51));
        warningLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(warningLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 190, 20));

        warningLabel1.setForeground(new java.awt.Color(255, 51, 51));
        warningLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(warningLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 190, 20));

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));

        editAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editAddressLabel.setForeground(new java.awt.Color(51, 153, 255));
        editAddressLabel.setText("Edit");
        editAddressLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        shippingAddressLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        shippingAddressLabel.setText("Shipping Address");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(shippingAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 595, Short.MAX_VALUE)
                .addComponent(editAddressLabel)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(shippingAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 40));

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLabel.setText("Address of the user");
        jPanel1.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        nameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLabel1.setText("Name of the User");
        jPanel1.add(nameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneNumberLabel.setText("Contact Number / Email of the user");
        jPanel1.add(phoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        cartPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 780, 130));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        cartPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 40));

        jPanel5.setBackground(new java.awt.Color(245, 245, 245));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Package 1 of 2 ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Shipped By");

        deliveryRider1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        deliveryRider1.setText("XXXXXXXX");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(deliveryRider1)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deliveryRider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cartPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 780, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage5.setForeground(new java.awt.Color(204, 204, 204));
        lblImage5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(lblImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 120));

        productName1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productName1.setText("Product Name");
        jPanel7.add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        productPrice1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productPrice1.setForeground(new java.awt.Color(215, 118, 25));
        productPrice1.setText("Product Price");
        jPanel7.add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        lblImage1.setForeground(new java.awt.Color(204, 204, 204));
        lblImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(lblImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 134, 129));

        qty1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qty1.setForeground(new java.awt.Color(102, 102, 102));
        qty1.setText("0");
        jPanel7.add(qty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 30, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Qty");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 15, -1, 30));

        lbl1Total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl1Total.setText("TOTAL");
        jPanel7.add(lbl1Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        cartPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 780, 170));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage4.setForeground(new java.awt.Color(204, 204, 204));
        lblImage4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.add(lblImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 120));

        productPrice2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productPrice2.setForeground(new java.awt.Color(215, 118, 25));
        productPrice2.setText("Product Price");
        jPanel8.add(productPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 20));

        lblImage2.setForeground(new java.awt.Color(204, 204, 204));
        lblImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.add(lblImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 134, 129));

        productName2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productName2.setText("Product Name");
        jPanel8.add(productName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 20));

        qty2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qty2.setForeground(new java.awt.Color(102, 102, 102));
        qty2.setText("0");
        jPanel8.add(qty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 30, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Qty");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 15, -1, 30));

        lbl2Total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl2Total.setText("TOTAL");
        jPanel8.add(lbl2Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        cartPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 780, 190));

        jPanel9.setBackground(new java.awt.Color(245, 245, 245));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Package 2 of 2 ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel17.setText("Shipped By");

        deliverRider2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        deliverRider2.setText("XXXXXXXX");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(36, 36, 36)
                .addComponent(deliverRider2)
                .addGap(29, 29, 29))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(deliverRider2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cartPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 780, -1));

        jPanel12.setBackground(new java.awt.Color(228, 166, 107));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        cartPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1540, 60));

        getContentPane().add(cartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1540, 740));

        jPanel2.setBackground(new java.awt.Color(228, 166, 107));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1542, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed

    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void gcashCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcashCheckBoxActionPerformed
        updatePaymentPanel();
    }//GEN-LAST:event_gcashCheckBoxActionPerformed

    private void cashOnDeliverCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashOnDeliverCBActionPerformed
        updatePaymentPanel();
    }//GEN-LAST:event_cashOnDeliverCBActionPerformed

    private void updatePaymentPanel() {
        if (cashOnDeliverCB.isSelected()) {
            cashOnDeliverPanel.setBorder(BorderFactory.createLineBorder(new Color(51, 153, 255)));
            cashOnDeliverySeperator.setForeground(new Color(51, 153, 255));
        } else {
            cashOnDeliverPanel.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
            cashOnDeliverySeperator.setForeground(new Color(204, 204, 204));
        }

        if (gcashCheckBox.isSelected()) {
            gcashPanel.setBorder(BorderFactory.createLineBorder(new Color(51, 153, 255)));
            gcashSeperator.setForeground(new Color(51, 153, 255));
        } else {
            gcashPanel.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
            gcashSeperator.setForeground(new Color(204, 204, 204));
        }

        cashOnDeliverPanel.revalidate();
        cashOnDeliverPanel.repaint();
        gcashPanel.revalidate();
        gcashPanel.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel addressLabel;
    private javax.swing.JButton btnCheckout;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JCheckBox cashOnDeliverCB;
    private javax.swing.JPanel cashOnDeliverPanel;
    private javax.swing.JSeparator cashOnDeliverySeperator;
    private javax.swing.JLabel deliverRider2;
    private javax.swing.JLabel deliveryRider1;
    private javax.swing.JLabel editAddressLabel;
    private javax.swing.JLabel editAddressLabel1;
    private javax.swing.JCheckBox gcashCheckBox;
    private javax.swing.JPanel gcashPanel;
    private javax.swing.JSeparator gcashSeperator;
    private javax.swing.JLabel gotoLandingPanelLogo;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl1Total;
    private javax.swing.JLabel lbl2Total;
    private javax.swing.JLabel lblDeliveryFee;
    private javax.swing.JLabel lblGrandTotal;
    public javax.swing.JLabel lblImage1;
    public javax.swing.JLabel lblImage2;
    public javax.swing.JLabel lblImage4;
    public javax.swing.JLabel lblImage5;
    public static javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel productName1;
    private javax.swing.JLabel productName2;
    private javax.swing.JLabel productPrice1;
    private javax.swing.JLabel productPrice2;
    private javax.swing.JLabel qty1;
    private javax.swing.JLabel qty2;
    public static javax.swing.JLabel shippingAddressLabel;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JLabel transactionNumberLabel;
    private javax.swing.JTextField voucherField;
    private javax.swing.JLabel warningLabel1;
    private javax.swing.JLabel warningLabel2;
    // End of variables declaration//GEN-END:variables
}
