/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package main_package;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author user
 */
public class ForgotPasswordDialog extends javax.swing.JDialog {

    /**
     * Creates new form ForgotPasswordForm
     */
    DatabaseManager dbManager = new DatabaseManager();

    public ForgotPasswordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

        togglePasswordVisibility(newPasswordField, forgotPasswordEye1);
        togglePasswordVisibility(confirmPasswordField, forgotPasswordEye2);
    }

    private int generatedOTP;

    private void togglePasswordVisibility(JPasswordField passwordField, JLabel eyeLabel) {
        eyeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            private boolean isVisible = false;

            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                isVisible = !isVisible;

                if (isVisible) {
                    passwordField.setEchoChar((char) 0);
                    eyeLabel.setIcon(new ImageIcon(getClass().getResource("/icons/closed.png"))); // open eye
                } else {
                    passwordField.setEchoChar('•');
                    eyeLabel.setIcon(new ImageIcon(getClass().getResource("/icons/open.png"))); // closed eye
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        verifyCode = new javax.swing.JButton();
        resetPasswordButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        forgotPasswordEye1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        forgotPasswordEye2 = new javax.swing.JLabel();
        codeWarningLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sendCode = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        registerWarningLabel1 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        newPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 133, 85));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Forgot Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 80));

        codeField.setBackground(new java.awt.Color(211, 189, 148));
        codeField.setBorder(null);
        codeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldActionPerformed(evt);
            }
        });
        jPanel1.add(codeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, 30));

        jPanel3.setBackground(new java.awt.Color(211, 189, 148));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/email icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, 40));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Enter New Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        verifyCode.setBackground(new java.awt.Color(137, 102, 38));
        verifyCode.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        verifyCode.setForeground(new java.awt.Color(255, 255, 255));
        verifyCode.setText("Verify Code");
        verifyCode.setBorder(null);
        verifyCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verifyCode.setFocusable(false);
        verifyCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyCodeActionPerformed(evt);
            }
        });
        jPanel1.add(verifyCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 100, 30));

        resetPasswordButton.setBackground(new java.awt.Color(137, 102, 38));
        resetPasswordButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        resetPasswordButton.setForeground(new java.awt.Color(30, 30, 30));
        resetPasswordButton.setText("Reset Password");
        resetPasswordButton.setBorder(null);
        resetPasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetPasswordButton.setFocusable(false);
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetPasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 390, 50));

        jPanel4.setBackground(new java.awt.Color(211, 189, 148));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 50, 40));

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Enter code");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jPanel5.setBackground(new java.awt.Color(211, 189, 148));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password confirmation icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 50, 40));

        jPanel6.setBackground(new java.awt.Color(211, 189, 148));

        forgotPasswordEye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgotPasswordEye1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgotPasswordEye1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 50, 40));

        jPanel7.setBackground(new java.awt.Color(211, 189, 148));

        forgotPasswordEye2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgotPasswordEye2)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forgotPasswordEye2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, 40));

        codeWarningLabel.setForeground(new java.awt.Color(252, 239, 216));
        codeWarningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(codeWarningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 380, 20));

        emailField.setBackground(new java.awt.Color(211, 189, 148));
        emailField.setBorder(null);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 320, 40));

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Enter email of your account");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        sendCode.setBackground(new java.awt.Color(137, 102, 38));
        sendCode.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        sendCode.setForeground(new java.awt.Color(255, 255, 255));
        sendCode.setText("Send Code");
        sendCode.setBorder(null);
        sendCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendCode.setFocusable(false);
        sendCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendCodeActionPerformed(evt);
            }
        });
        jPanel1.add(sendCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, 30));

        jSeparator1.setBackground(new java.awt.Color(242, 242, 243));
        jSeparator1.setForeground(new java.awt.Color(206, 206, 203));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 380, 20));

        registerWarningLabel1.setForeground(new java.awt.Color(252, 239, 216));
        registerWarningLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(registerWarningLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 360, 20));

        confirmPasswordField.setBackground(new java.awt.Color(211, 189, 148));
        confirmPasswordField.setBorder(null);
        confirmPasswordField.setEnabled(false);
        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 280, 40));

        newPasswordField.setBackground(new java.awt.Color(211, 189, 148));
        newPasswordField.setBorder(null);
        newPasswordField.setEnabled(false);
        newPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(newPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 280, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldActionPerformed

    }//GEN-LAST:event_codeFieldActionPerformed

    private void verifyCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyCodeActionPerformed
        String enteredCode = codeField.getText().trim();

        if (enteredCode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the code.");
            return;
        }

        // Check if numeric
        if (!enteredCode.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Code must be numbers only.");
            return;
        }

        int code = Integer.parseInt(enteredCode);

        if (code == generatedOTP) {
            JOptionPane.showMessageDialog(this, "Code verified!");

            // SHOW new password + confirm password fields
            newPasswordField.setEnabled(true);
            confirmPasswordField.setEnabled(true);
            resetPasswordButton.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(this, "Incorrect code!");
        }
    }//GEN-LAST:event_verifyCodeActionPerformed

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        String newPass = new String(newPasswordField.getPassword());
        String confirmPass = new String(confirmPasswordField.getPassword());

        // Basic validation
        if (newPass.isEmpty() || confirmPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all password fields.");
            return;
        }

        if (newPass.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters.");
            return;
        }

        if (!newPass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.");
            return;
        }

        // Hash using BCrypt
        String hashedPassword = BCrypt.hashpw(newPass, BCrypt.gensalt());

        // Update DB
        if (dbManager.updatePasswordByEmail(emailField.getText().trim(), hashedPassword)) {
            JOptionPane.showMessageDialog(this, "Password reset successful!");
            dispose();  // close window after success
        } else {
            JOptionPane.showMessageDialog(this, "Failed to reset password.");
        }
    }//GEN-LAST:event_resetPasswordButtonActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void sendCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendCodeActionPerformed
        String email = emailField.getText().trim();

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email.");
            return;
        }

        if (!dbManager.checkEmailExist(email)) {
            JOptionPane.showMessageDialog(this, "Email not found!");
            return;
        }

// Generate 6-digit OTP
        generatedOTP = 100000 + new Random().nextInt(900000);

// Create timer (delay only once)
        javax.swing.Timer timer = new javax.swing.Timer(1500, e -> {
            JOptionPane.showMessageDialog(this, "Your reset code: " + generatedOTP);
        });
        timer.setRepeats(false); // ❗ VERY IMPORTANT
        timer.start();

        JOptionPane.showMessageDialog(this, "A verification code has been sent.");
    }//GEN-LAST:event_sendCodeActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        confirmPasswordField.transferFocus();
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void newPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ForgotPasswordDialog dialog = new ForgotPasswordDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codeField;
    private javax.swing.JLabel codeWarningLabel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel forgotPasswordEye1;
    private javax.swing.JLabel forgotPasswordEye2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel registerWarningLabel1;
    private javax.swing.JButton resetPasswordButton;
    private javax.swing.JButton sendCode;
    private javax.swing.JButton verifyCode;
    // End of variables declaration//GEN-END:variables
}
