/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adjacencylist;

import javax.swing.JLabel;
public class FunctionFrame extends javax.swing.JFrame {

    /**
     * Creates new form FunctionFrame
     */
    public FunctionFrame() {
        initComponents();
    }
    
    static DatabaseManager dbManager = new DatabaseManager();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minusButtonOne = new javax.swing.JButton();
        addButtonOne = new javax.swing.JButton();
        minusButtonTwo = new javax.swing.JButton();
        addButtonTwo = new javax.swing.JButton();
        minusButtonThree = new javax.swing.JButton();
        addButtonThree = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quantityOneLabel = new javax.swing.JLabel();
        quantityTwoLabel = new javax.swing.JLabel();
        quantityThreeLabel = new javax.swing.JLabel();
        addAllButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        minusButtonOne.setText("-");
        minusButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonOneActionPerformed(evt);
            }
        });

        addButtonOne.setText("+");
        addButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonOneActionPerformed(evt);
            }
        });

        minusButtonTwo.setText("-");
        minusButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonTwoActionPerformed(evt);
            }
        });

        addButtonTwo.setText("+");
        addButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonTwoActionPerformed(evt);
            }
        });

        minusButtonThree.setText("-");
        minusButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonThreeActionPerformed(evt);
            }
        });

        addButtonThree.setText("+");
        addButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonThreeActionPerformed(evt);
            }
        });

        jLabel1.setText("Zesto");

        jLabel2.setText("C2");

        jLabel3.setText("Ethyl Alcohol");

        quantityOneLabel.setText("0");

        quantityTwoLabel.setText("0");

        quantityThreeLabel.setText("0");

        addAllButton.setText("Add to inventory");
        addAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(minusButtonThree)
                        .addGap(18, 18, 18)
                        .addComponent(quantityThreeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButtonThree))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(minusButtonTwo)
                        .addGap(18, 18, 18)
                        .addComponent(quantityTwoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButtonTwo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(minusButtonOne)
                        .addGap(18, 18, 18)
                        .addComponent(quantityOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButtonOne)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addAllButton)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minusButtonOne)
                    .addComponent(addButtonOne)
                    .addComponent(jLabel1)
                    .addComponent(quantityOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minusButtonTwo)
                    .addComponent(addButtonTwo)
                    .addComponent(jLabel2)
                    .addComponent(quantityTwoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minusButtonThree)
                    .addComponent(addButtonThree)
                    .addComponent(jLabel3)
                    .addComponent(quantityThreeLabel))
                .addGap(29, 29, 29)
                .addComponent(addAllButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    private void minusButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonOneActionPerformed
        String t = quantityOneLabel.getText();
        int currentQuantity = Integer.parseInt(t);
        
        if(currentQuantity >0){
        currentQuantity--;
        quantityOneLabel.setText(String.valueOf(currentQuantity));
        }
        
    }//GEN-LAST:event_minusButtonOneActionPerformed

    private void addButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonOneActionPerformed
        String t = quantityOneLabel.getText();
        int currentQuantity = Integer.parseInt(t);
        
        currentQuantity++;
        quantityOneLabel.setText(String.valueOf(currentQuantity)); 
    }//GEN-LAST:event_addButtonOneActionPerformed

    private void addButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonTwoActionPerformed
       String t = quantityTwoLabel.getText();
        int currentQuantity = Integer.parseInt(t);
        currentQuantity++;
        quantityTwoLabel.setText(String.valueOf(currentQuantity));
    }//GEN-LAST:event_addButtonTwoActionPerformed

    private void addButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonThreeActionPerformed
        String t = quantityThreeLabel.getText();
        int currentQuantity = Integer.parseInt(t);
        currentQuantity++;
        quantityThreeLabel.setText(String.valueOf(currentQuantity));
    }//GEN-LAST:event_addButtonThreeActionPerformed

    private void minusButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonThreeActionPerformed
        String t = quantityThreeLabel.getText();
        int currentQuantity = Integer.parseInt(t);
        
         if(currentQuantity >0){
        currentQuantity--;
        quantityThreeLabel.setText(String.valueOf(currentQuantity));
         }
    }//GEN-LAST:event_minusButtonThreeActionPerformed

    private void minusButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonTwoActionPerformed
        String t = quantityTwoLabel.getText();
        int currentQuantity = Integer.parseInt(t);
         if(currentQuantity >0){
        currentQuantity--;
        quantityTwoLabel.setText(String.valueOf(currentQuantity));
         }
    }//GEN-LAST:event_minusButtonTwoActionPerformed

    private void addAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAllButtonActionPerformed
       int qty1 = Integer.parseInt(quantityOneLabel.getText());
       int qty2 = Integer.parseInt(quantityTwoLabel.getText());
       int qty3 = Integer.parseInt(quantityThreeLabel.getText());
       
       dbManager.update(qty1, 1);
       dbManager.update(qty2, 2);
       dbManager.update(qty3, 3);
       
       quantityOneLabel.setText("0");
       quantityTwoLabel.setText("0");
       quantityThreeLabel.setText("0");    
       
       dbManager.display();
    }//GEN-LAST:event_addAllButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunctionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunctionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunctionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunctionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FunctionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAllButton;
    private javax.swing.JButton addButtonOne;
    private javax.swing.JButton addButtonThree;
    private javax.swing.JButton addButtonTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton minusButtonOne;
    private javax.swing.JButton minusButtonThree;
    private javax.swing.JButton minusButtonTwo;
    private javax.swing.JLabel quantityOneLabel;
    private javax.swing.JLabel quantityThreeLabel;
    private javax.swing.JLabel quantityTwoLabel;
    // End of variables declaration//GEN-END:variables
}
